### ISSUE TITLE
request: Bump package-lock.json version too

### ISSUE THREAD

**Issue by artrz** [favware/cliff-jumper#192]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Currently, only the version in package.json is bumped, package-lock.json being ignored.

### Desired solution

Bump the version contained in package-lock.json too.

### Alternatives considered

Skip git tagging, update and stage the lock file, amend the commit, and manually tag the new commit, but this is not feasible as a repetitive task.

**Comment by favna** [comment]
This should be solved by setting the `--install` (or `install: true` in the config file) flag as it will run `npm install` after bumping.

**Comment by artrz** [comment]
Thanks, I missed that setting. Great package by the way!
